name: Trigger S3 Upload

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger on

jobs:
  call-upload-workflow:
    uses: your-org-or-repo-name/.github/workflows/upload-binaries-to-s3.yml@main
    with:
      region: "eu-west-2"  # Change to your AWS region
    secrets:
      bucket_name: ${{ secrets.AWS_S3_BUCKET }}
      role_to_assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
